#!/bin/sh                                                                                                                                                    
#SBATCH --job-name=psf_kicp                                                                                                         
#SBATCH --output=stdout/psf_kicp.out                                                                                                 
#SBATCH --error=stdout/psf_kicp.err                                                                                                  
#SBATCH --time=01:00:00                                                                                                                                       
#SBATCH --nodes=3                                                                                                                                             
#SBATCH --ntasks-per-node=16                                                                                                                                 
#SBATCH --exclusive                                                                                                                                          
#SBATCH --partition=kicp                                                                                                                                    
#SBATCH --account=kicp                                                                                                                                  

source ~/SHEAR/mcal_sim_test/lucas_env/SOURCE_LUCAS

export NTASKS=$SLURM_NTASKS

srun run_psf_KICP.sh
