#!/bin/sh                        
#SBATCH --job-name=psf_kicp                                                                                                         
#SBATCH --output=stdout/psf_kicp_%j.out                                                                             
#SBATCH --error=stdout/psf_kicp_%j.err      
#SBATCH --time=48:00:00                                                 
#SBATCH --nodes=10                                                                     
#SBATCH --ntasks-per-node=16   
#SBATCH --cpus-per-task=1
#SBATCH --exclusive                                                                                                            
#SBATCH --partition=kicp                                                                 
#SBATCH --account=kicp                                                                                                                                 

source ~/SHEAR/mcal_sim_test/lucas_env/SOURCE_LUCAS

export NTASKS=$SLURM_NTASKS
export DELETE_DIR=True

srun run_psf_KICP.sh
