#!/bin/sh                        
#SBATCH --job-name=rhos          
#SBATCH --output=stdout/rhos_chihway_%j.out                                                                             
#SBATCH --error=stdout/rhos_chihway_%j.err      
#SBATCH --time=10:00:00                                                 
#SBATCH --nodes=4                                                                     
#SBATCH --ntasks-per-node=1   
#SBATCH --cpus-per-task=40
#SBATCH --exclusive      
#SBATCH --partition=chihway                                                                 
#SBATCH --account=pi-chihway                                                                                                                             
source ~/SHEAR/mcal_sim_test/lucas_env/SOURCE_LUCAS

export NTASKS=$SLURM_NTASKS

srun run_treecorr_KICP.sh
