#!/bin/sh                        
#SBATCH --job-name=rhos          
#SBATCH --output=stdout/rhos_kicpaa_%j.out                                                                             
#SBATCH --error=stdout/rhos_kicpaa_%j.err      
#SBATCH --time=10:00:00                                                 
#SBATCH --nodes=4                                                                     
#SBATCH --ntasks-per-node=1   
#SBATCH --cpus-per-task=28
#SBATCH --exclusive      
#SBATCH --partition=kicpaa                                                                 
#SBATCH --account=kicpaa      
                                                                                                             
source /home/secco/SOURCE_treecorr          

export NTASKS=$SLURM_NTASKS

srun run_treecorr_KICP.sh
