#!/bin/sh                        
#SBATCH --job-name=psf_kicpaa                                                                                                         
#SBATCH --output=stdout/psf_kicpaa_%j.out                                                                                                 
#SBATCH --error=stdout/psf_kicpaa_%j.err                                                                                                  
#SBATCH --time=00:10:00                                                 
#SBATCH --nodes=3                                                                     
#SBATCH --ntasks-per-node=28   
#SBATCH --cpus-per-task=1
#SBATCH --exclusive                                                                                                            
#SBATCH --partition=kicpaa                                                                                                                
#SBATCH --account=kicpaa                                                                                                                                 

source ~/SHEAR/mcal_sim_test/lucas_env/SOURCE_LUCAS

export NTASKS=$SLURM_NTASKS
export DELETE_DIR=True

srun run_psf_KICP.sh
